name: Sync Technical Documentation

on:
  push:
    branches:
      - main
    paths:
      - "src/lib/api/error/error-codes/pi-error-codes.ts"
      - "src/core/enums/chain-id.ts"

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Checkout Docs Repo
        uses: actions/checkout@v4
        with:
          repository: hydric-org/docs
          token: ${{ secrets.SYNC_DOCS_PAT }}
          path: docs-repo
          persist-credentials: true

      - name: Generate Error Docs
        run: |
          npx ts-node -r tsconfig-paths/register scripts/generate-error-docs.ts docs-repo/snippets/custom-error-codes.mdx

      - name: Generate Supported Chains Docs
        run: |
          npx ts-node -r tsconfig-paths/register scripts/generate-chain-docs.ts docs-repo/snippets/supported-blockchains/liquidity-pools.mdx

      - name: Commit and Push Changes
        working-directory: docs-repo
        run: |
          if [[ -n $(git status -s) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add snippets/custom-error-codes.mdx snippets/supported-blockchains/liquidity-pools.mdx
            git commit -m "docs: automatic update of technical reference snippets"
            git push origin main
          else
            echo "No changes in documentation."
          fi
